modLoader="javafml"
loaderVersion="[46,)"
license="MIT"

[[mods]]
   modId="soulless_steeds"
   version="1.0.0"
   displayName="Soulless Steeds"
   authors="ThatGravyBoat"
   description="Adds natural spawning zombie horses and wither skeleton horses."

[[dependencies.soulless_steeds]]
   modId="forge"
   mandatory=true
   versionRange = "[46,)"
   ordering="NONE"
   side="BOTH"

[[dependencies.soulless_steeds]]
   modId="minecraft"
   mandatory=true
   versionRange="[1.20,)"
   ordering="NONE"
   side="BOTH"
